---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc-active
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc-preview
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
---
{{- if .Values.InternalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-openapi-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
  {{- with .Values.InternalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.InternalService.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: {{ .Values.InternalService.name }}
      port: {{ .Values.InternalService.port }}
      targetPort: {{ .Values.InternalService.targetPort }}
      protocol: {{ .Values.InternalService.protocol }}
{{- end }}
