### external to service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vsvc
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.host }}
  gateways:
    - {{ .Values.namespace }}/istio-gateway
  http:
  - name: 
    route:
    - destination:
        host: "{{ .Values.appName }}-svc-active"  # name of k8s service