---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | toString }}
          imagePullPolicy: Always
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ .port }}
            {{- end }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          {{- end }}
          env:
            {{- toYaml .Values.envVars | nindent 12 }}
      {{- if .Values.volume.enabled }}
      volumes:
      - name: test
        secret:
          items:
          - key: test
            path: test
          secretName: test-secret
      {{- end }}
  strategy:
    blueGreen:
      autoPromotionEnabled: {{ .Values.autoPromotionEnabled }}
      activeService: {{ .Values.appName }}-svc-active
      previewService: {{ .Values.appName }}-svc-preview
