# Source: prometheus/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prometheus
    chart: {{ .Values.HelmChartVersion }}
    heritage: Helm
  name: prometheus
  namespace: istio-system
  annotations:
    {}