- op: add
  path: /spec/source/helm/values
  value: |-
    serviceAccount:
      name: external-secrets
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::086230238707:role/eks-demodapne2-uuhx-external-secrets
