# Source: kiali-server/templates/role-controlplane.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kiali-controlplane
  namespace: {{ .Values.namespace }}
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"
    helm.sh/chart: {{ .Values.HelmChartVersion }}
    app.kubernetes.io/version: {{ .Values.HelmAppVersion }}
    version: {{ .Values.HelmAppVersion }}
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - list
- apiGroups: [""]
  resourceNames:
  - cacerts
  - istio-ca-secret
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch