# Source: kiali-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ .Values.namespace }}
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"
    helm.sh/chart: {{ .Values.HelmChartVersion }}
    app.kubernetes.io/version: {{ .Values.HelmAppVersion }}
    version: {{ .Values.HelmAppVersion }}
  annotations:
spec:
  ports:
  - name: http
    protocol: TCP
    port: 20001
  - name: http-metrics
    protocol: TCP
    port: 9090
  selector:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali