# Source: kiali-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: {{ .Values.namespace }}
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"
    helm.sh/chart: {{ .Values.HelmChartVersion }}
    app.kubernetes.io/version: {{ .Values.HelmAppVersion }}
    version: {{ .Values.HelmAppVersion }}