apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../../common/argocd
  - karpenter-provisioner.yaml
patches:
  # Setup the git repository metadata in External Secret
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: k8s-env-repo
    path: patches/setup-git-repository.yaml

  # Patch argocd configmap for okta login
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    path: patches/add-argocd-configmap-data.yaml

  # specify argocd ingress host and certificate
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: argocd-ingress
    path: patches/specify-ingress-host-certificate.yaml

  # Add the bootstrap variables
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: bootstrap
    path:  patches/add-bootstrap-variables.yaml

  # Add the service account to external secret to get secret values
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: external-secrets
    path: patches/attach-external-secret-serviceaccount.yaml
