---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/namejsjeongkr/devops_k8s_env
    targetRevision: main
    path: apps/sample-bluegreen/charts
    helm:
      valueFiles:
        - ../../../demod_apnortheast2/demodapne2-abcd/sample-project/sample-app/bluegreen/values.yaml
        - ../../../demod_apnortheast2/demodapne2-abcd/sample-project/sample-app/bluegreen/image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: blugreen
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
