---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/svc-proto-dev/k8s-env
    targetRevision: develop
    path: apps/sample-canary/charts
    helm:
      valueFiles:
        - ../../../rbmd_apnortheast2/rbmdapne2-dfbv/sample-app/canary/values.yaml
        - ../../../rbmd_apnortheast2/rbmdapne2-dfbv/sample-app/canary/image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: canary
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
